export const SITE_NAME = 'ViStore'
export const SITE_TITLE = 'ViStore - Shop Smart, Live Better'
export const SITE_URL = 'https://www.oxabags.com/'
export const SITE_DESCRIPTION =
    'Manufacturer, Wholesaler & Exporter of Jute bags, Cotton Bag for Corporate Events & Exhibitions'
export const SITE_KEYWORDS = 'Jute bags, Cotton Bag, Canvas Bags, File Folders, Denim Bags, Pouches'
export const SITE_CATEGORY = 'Shopping'
export const SITE_IMAGE = 'https://www.oxabags.com/og.webp'
export const OWNER_NAME = 'Khanh'
export const OWNER_EMAIL = 'example@gmail.com'
export const OWNER_PHONE_1 = '0123456789'
export const OWNER_PHONE_2 = '9876543210'
export const COMPANY_NAME = 'ViStore Enterprises'
export const COMPANY_ADDRESS =
    'FPT Polytechnic Building, Gate 2, 13 Trinh Van Bo Street, Xuan Phuong, Nam Tu Liem, Hanoi'
